# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zack Piper's Website
email: zpipe07@gmail.com
description: Website of Zack Piper the front-end web developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.zackpiper.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Defaults
defaults:
  - scope:
      path: "_work"
      type: work
    values:
      layout: work-detail

# Collections
collections:
  work:
    output: true
    permalink: /work/:title/

# Excludes
exclude:
- node_modules
- gulpfile.js
- package.json
- readme.md